operation_mode: prediction

general:
  display_figures: False
  
model: 
  framework: 'torch'
  model_name: 'mobilenetv2_w035_pt' 
  pretrained: True
  pretrained_dataset: "imagenet"
  input_shape: [3, 224, 224]

dataset:
  dataset_name: "imagenet" # options "flowers102", "food101", "imagenet"
  class_names: ''
  classes_file_path: ./datasets/deployment_labels_imagenet.txt
  #data_dir: "/local/datasets/" # there shud be imagenet folder inside this directory # can also be used for quantization
  num_classes: 1000 # change according to your dataset
  # train_split: "train"
  # val_split: "validation"
  prediction_path: "/local/datasets/ic_imagenet_2012/val/n01440764/"
  workers: 4 
  no_prefetcher: true

preprocessing: 
  rescaling: # Not used for Torch Image Classification
    scale: None # Not used for Torch Image Classification
    offset: None # Not used for Torch Image Classification
  resizing:
    interpolation: random # 'random' means random.choice(["bilinear", "bicubic"]). This will be used for training data and bilinear is fixed for test data 
    aspect_ratio: fit # fit is the only aspect_ratio supported for torch image classification.
  color_mode: rgb # rgb is the only color_mode supported  for torch image classification.
  normalization:
    mean: [0.485, 0.456, 0.406] # Subtracted from each channel: (x - mean) / std
    std: [0.229, 0.224, 0.225] # Divides each channel after mean subtraction

prediction:
   profile: profile_O3
   input_type: uint8     # int8 / uint8 / float32
   output_type: int8     # int8 / uint8 / float32
   input_chpos: chlast   # chlast / chfirst
   output_chpos: chlast  # chlast / chfirst
   target: stedgeai_n6 # host, stedgeai_host, stedgeai_n6

tools:
   stedgeai:
      path_to_stedgeai: C:/ST/STEdgeAI/3.0/Utilities/windows/stedgeai.exe
       
mlflow:
  uri: ./pt/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./pt/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}